remotes::install_version("tidyverse", version = "1.3.1", clean = T)
remotes::install_version("targets", version = "0.13.5", clean = T)
remotes::install_version("tarchetypes", version = "0.7.1", clean = T)
remotes::install_version("rmarkdown", version = "2.16", clean = T)
remotes::install_version("future.callr", version = "0.8.0", clean = T)
remotes::install_version("IRkernel", version = "1.3", clean = T)
remotes::install_version("visNetwork", version = "2.1.2", clean = T)
remotes::install_version("here", version = "1.0.1", clean = T)
remotes::install_version("Matrix.utils", version = "0.9.8", clean = T)
remotes::install_version("SoupX", version = "1.6.2", clean = T)
remotes::install_version('speedglm', '0.3-4', repos = 'https://packagemanager.rstudio.com/cran/2023-03-31')